# JPA 설정: DB에 테이블이 없으면 자동으로 생성해줌
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL 방언 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL 쿼리 로그 출력 (선택 사항)
spring.jpa.show-sql=true
